package com.example.zephyrevents.repository;

// The following Javadoc comments were generated by Anthropic, Claude,
// "Generate Javadoc comments for EventRepository.java", 2026-03-12
// References used in this file:
// https://firebase.google.com/docs/firestore/manage-data/add-data#java_2
// https://firebase.google.com/docs/database/admin/retrieve-data#java
// https://developer.android.com/reference/android/util/Log

import android.util.Log;
import androidx.annotation.NonNull;
import com.example.zephyrevents.model.Event;
import java.util.ArrayList;
import java.util.List;
import com.example.zephyrevents.util.TimeHelper;
import com.google.android.gms.tasks.OnFailureListener;
import com.google.android.gms.tasks.OnSuccessListener;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.QueryDocumentSnapshot;
import com.google.firebase.firestore.QuerySnapshot;


/**
 * Repository class for managing Event data in Firestore.
 * Provides methods for creating, reading, updating, and deleting events,
 * as well as querying events by time.
 */
public class EventRepository {

    private final FirebaseFirestore db;
    private static final String TAG = "EventRepository";

    /**
     * Default constructor. Uses the production Firestore instance.
     */
    public EventRepository() {
        db = FirebaseFirestore.getInstance();
    }

    /**
     * Constructor for dependency injection, primarily used for testing.
     *
     * @param db A FirebaseFirestore instance to use instead of the default.
     */
    public EventRepository(FirebaseFirestore db) {
        this.db = db;
    }
    /**
     * Persists an event to Firestore. Validates that the event and its ID are non-null
     * and non-empty before making a network call.
     *
     * @param event    The event to save. Must not be null and must have a valid ID.
     * @param callback Called with null on success, or an exception on failure.
     */
    public void saveEvent(Event event, RepositoryCallback<Void> callback) {
        if (event == null) {
            var e = new IllegalArgumentException("Event cannot be null");
            Log.w(TAG, "event passed had value of null", e);
            callback.onFailure(e);
            return;
        }
        if (event.getEventId() == null || event.getEventId().trim().isEmpty()){
            var e = new IllegalArgumentException("Event id passed has no value");
            Log.w(TAG, "event has no associated id", e);
            callback.onFailure(e);
            return; // exit before network call.
        }
        db.collection(Collections.EVENTS)
                .document(event.getEventId())
                .set(event)
                .addOnSuccessListener(new OnSuccessListener<Void>() {
                    @Override
                    public void onSuccess(Void aVoid) {
                        Log.d(TAG, "Firestore event added object id: " + event.getEventId());
                        callback.onSuccess(null);
                    }
                })
                .addOnFailureListener(new OnFailureListener() {
                    @Override
                    public void onFailure(@NonNull Exception e) {
                        Log.w(TAG, "Error writing document", e);
                        callback.onFailure(e);
                    }
                });

    }

    /**
     * Creates a new event in Firestore. Delegates to saveEvent.
     *
     * @param event    The event to create.
     * @param callback Called with null on success, or an exception on failure.
     */
    public void createEvent(Event event, RepositoryCallback<Void> callback){
        saveEvent(event, callback);
    }

    /**
     * Updates an existing event in Firestore by overwriting it. Delegates to saveEvent.
     * Note: this uses set() rather than update(), which can cause a race condition
     * if two clients update different fields simultaneously.
     *
     * @param event    The event to update.
     * @param callback Called with null on success, or an exception on failure.
     */
    public void updateEvent(Event event, RepositoryCallback<Void> callback) {
        saveEvent(event, callback);
    }
    /**
     * Retrieves a single event from Firestore by its ID.
     * Returns an exception via callback if the ID is invalid or the document does not exist.
     *
     * @param id       The Firestore document ID of the event.
     * @param callback Called with the Event object on success, or an exception on failure.
     */
    public void getEventById(String id, RepositoryCallback<Event> callback) {
        if (id == null || id.trim().isEmpty()){
            var e = new IllegalArgumentException("event id passed has no value");
            Log.w(TAG, "invalid event id", e);
            callback.onFailure(e);
            return; // exit before network call.
        }
        db.collection(Collections.EVENTS)
                .document(id)
                .get()
                .addOnSuccessListener(new OnSuccessListener<DocumentSnapshot>() {
                    @Override
                    public void onSuccess(DocumentSnapshot doc) {
                        // is onSuccess guaranteed to be not null? Idk tbh.
                        if (doc == null || !doc.exists()){
                            var e = new IllegalArgumentException("document returned doesn't exist");
                            Log.w(TAG, "event document not found for id: "+id, e);
                            callback.onFailure(e);
                        }else{
                                Log.d(TAG, "DocumentSnapshot data: " + doc.getData());
                                callback.onSuccess(doc.toObject(Event.class));
                        }
                    }
                })
                .addOnFailureListener(new OnFailureListener() {
            @Override
            public void onFailure(@NonNull Exception e) {
                Log.w(TAG, "error getting doc by id: "+id+"\n exception returned: ", e);
                callback.onFailure(e);
            }
        });

    }

    /**
     * Deletes an event from Firestore by its ID.
     * Also performs a cascade delete of any waitlist documents associated with the event.
     *
     * @param eventId  The Firestore document ID of the event to delete.
     * @param callback Called with null on success, or an exception on failure.
     */
    public void deleteEvent(String eventId, RepositoryCallback<Void> callback) {
        db.collection(Collections.EVENTS).document(eventId).delete()
                .addOnSuccessListener(aVoid -> {
                    // Cascade delete associated waitlists
                    db.collection(com.example.zephyrevents.repository.Collections.WAITLIST)
                            .whereEqualTo("eventId", eventId)
                            .get()
                            .addOnSuccessListener(querySnapshot -> {
                                for (DocumentSnapshot doc : querySnapshot) {
                                    doc.getReference().delete();
                                }
                            });

                    callback.onSuccess(null);
                })
                .addOnFailureListener(callback::onFailure);
    }

    /**
     * Retrieves all events from Firestore regardless of time.
     *
     * @param callback Called with a list of all events on success, or an exception on failure.
     */
    public void getAllEvents(RepositoryCallback<List<Event>> callback){
        db.collection(Collections.EVENTS)
                .get()
                .addOnSuccessListener(new OnSuccessListener<QuerySnapshot>() {
                    @Override
                    public void onSuccess(QuerySnapshot querySnapshot) {


                        List<Event> events = new ArrayList<>();

                        for (QueryDocumentSnapshot doc : querySnapshot) {
                            Event event = doc.toObject(Event.class);
                            events.add(event);
                        }

                        callback.onSuccess(events);
                    }
                })
                    .addOnFailureListener(new OnFailureListener() {
                        @Override
                        public void onFailure(@NonNull Exception e) {
                            Log.w(TAG, "Error getting events", e);
                            callback.onFailure(e);
                        }
                    });
    }
    /**
     * Retrieves all events whose end time is in the future, meaning they have not yet ended.
     *
     * @param callback Called with a list of open events on success, or an exception on failure.
     */
    public void getOpenEvents(RepositoryCallback<List<Event>> callback){
        db.collection(Collections.EVENTS)
                .whereGreaterThan("time.endTime", TimeHelper.now())
                .get()
                .addOnSuccessListener(new OnSuccessListener<QuerySnapshot>() {
                    @Override
                    public void onSuccess(QuerySnapshot querySnapshot) {


                        List<Event> events = new ArrayList<>();

                        for (QueryDocumentSnapshot doc : querySnapshot) {
                            Event event = doc.toObject(Event.class);
                            events.add(event);
                        }

                        callback.onSuccess(events);
                    }
                })
                .addOnFailureListener(new OnFailureListener() {
                    @Override
                    public void onFailure(@NonNull Exception e) {
                        Log.w(TAG, "Error getting events", e);
                        callback.onFailure(e);
                    }
                });
    }
    /**
     * Retrieves all events whose start time is in the future.
     *
     * @param callback Called with a list of upcoming events on success, or an exception on failure.
     */
       public void getUpcomingEvents(RepositoryCallback<List<Event>> callback){
        db.collection(Collections.EVENTS)
                .whereGreaterThan("time.startTime", TimeHelper.now())
                .get()
                .addOnSuccessListener(new OnSuccessListener<QuerySnapshot>() {
                    @Override
                    public void onSuccess(QuerySnapshot querySnapshot) {


                        List<Event> events = new ArrayList<>();

                        for (QueryDocumentSnapshot doc : querySnapshot) {
                            Event event = doc.toObject(Event.class);
                            events.add(event);
                        }

                        callback.onSuccess(events);
                    }
                })
                .addOnFailureListener(new OnFailureListener() {
                    @Override
                    public void onFailure(@NonNull Exception e) {
                        Log.w(TAG, "Error getting events", e);
                        callback.onFailure(e);
                    }
                });
    }
    /**
     * Retrieves all events that are currently happening, meaning their start time is in the past
     * and their end time is in the future.
     *
     * @param callback Called with a list of current events on success, or an exception on failure.
     */
    public void getEventsHappeningNow(RepositoryCallback<List<Event>> callback){
        db.collection(Collections.EVENTS)
                .whereLessThanOrEqualTo("time.startTime", TimeHelper.now())
                .whereGreaterThanOrEqualTo("time.endTime", TimeHelper.now())
                .get()
                .addOnSuccessListener(new OnSuccessListener<QuerySnapshot>() {
                    @Override
                    public void onSuccess(QuerySnapshot querySnapshot) {


                        List<Event> events = new ArrayList<>();

                        for (QueryDocumentSnapshot doc : querySnapshot) {
                            Event event = doc.toObject(Event.class);
                            events.add(event);
                        }

                        callback.onSuccess(events);
                    }
                })
                .addOnFailureListener(new OnFailureListener() {
                    @Override
                    public void onFailure(@NonNull Exception e) {
                        Log.w(TAG, "Error getting events", e);
                        callback.onFailure(e);
                    }
                });
    }
}