name: Deploy static content to Pages

on:
  push:
    branches: ["development"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make script executable
<<<<<<< HEAD
        run: chmod +x ./scripts/gen_javadoc.sh

      - name: Generate Javadocs
        run: ./scripts/gen_javadoc.sh
=======
        run: chmod +x ./scripts/gen-javadoc.sh

      - name: Generate Javadocs
        run: ./scripts/gen-javadoc.sh
>>>>>>> origin/main

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./javadoc

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
